---
minimum_pre_commit_version: 4.5.1
exclude: ^(docs)

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.10.1
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Hooks that actively "change" files (formatters etc.)
# ----------------------------------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md

# isort (in black-compatibility mode)
- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --filter-files

# Black (uncompromising) Python code formatter
- repo: https://github.com/psf/black
  rev: 25.12.0
  hooks:
  - id: black
    args:
    - --target-version
    - py313

# Hooks that do not "change" files (linters etc.)
# --------------------------------

# MyPy
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.19.1
#  hooks:
#  - id: mypy
#    files: ^app
#    args:
#    - --python-version=3.12
#    additional_dependencies:
#    - types-requests

# Pylint
# To check import errors we need to install every package
# used by the DM. This is often impractical on the client,
# and so we disable import errors on pre-commit and rely
# on this category of test in the CI stage. Consequently,
# pylint may pass on pre-commit but fail in CI - but at least
# the user has done 90% of the lint checks before the code
# hits the server.
- repo: https://github.com/pycqa/pylint
  rev: v4.0.4
  hooks:
  - id: pylint
    args:
    - --disable=import-error
    - --py-version=3.13
